trigger:
- 'main'

variables:
  releaseBranchName: 'main'
  builderImage: 'jekyll/builder:latest'

stages:
  - stage: 'Build'
    displayName: 'Build the site'
    variables:
      BUILD_INFO: '$(Build.DefinitionName) $(Build.BuildId) $(Build.BuildNumber) - $(Build.SourceBranchName)'
    jobs:
      - job: 'Build'
        displayName: 'Build job'
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: 'Run Jekyll'
            inputs:
              command: run
              arguments: -v $(build.sourcesDirectory):/srv/jekyll:rw -v $(build.sourcesDirectory)/.jekyll-cache:/srv/jekyll/.jekyll-cache:rw -v $(build.binariesDirectory):/srv/jekyll/_site:rw ${{variables.builderImage}} jekyll build --future
          - task: CopyFiles@2
            displayName: 'copy _site'
            inputs:
              SourceFolder: '_site'
              TargetFolder: '$(Build.binariesDirectory)'         
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.binariesDirectory)'
              ArtifactName: site