trigger:
- 'main'

variables:
  releaseBranchName: 'main'
  builderImage: 'jekyll/builder:latest'

stages:
  - stage: 'Build'
    displayName: 'Build the site'
    variables:
      BUILD_INFO: '$(Build.DefinitionName) $(Build.BuildId) $(Build.BuildNumber) - $(Build.SourceBranchName)'
    jobs:
      - job: 'Build'
        displayName: 'Build job'
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: 'Run Jekyll'
            inputs:
              command: run
              arguments: '{builderImage} -v $(build.sourcesDirectory):/srv/jekyll -v $(build.sourcesDirectory)/.jekyll-cache:/srv/jekyll/.jekyll-cache -v $(build.binariesDirectory):/srv/srv/jekyll/_site jekyll build --future'





          #     containerRegistryType: 'Container Registry'
          #     action: 'Run an image'
          #     imageName: 'jekyll/builder:latest'
          #     arguments:
          #       - BUILD_INFO="$(Build.DefinitionName) $(Build.BuildId) $(Build.BuildNumber) - $(Build.SourceBranchName)"
          #     volumes: |
          #       $(build.sourcesDirectory):/srv/jekyll
          #       $(build.sourcesDirectory)/.jekyll-cache:/srv/jekyll/.jekyll-cache
          #       $(build.binariesDirectory):/srv/jekyll/_site
          #     containerCommand: 'jekyll build --future'
          #     detached: false

          # - task: CopyFiles@2
          #   displayName: 'copy _site'
          #   inputs:
          #     SourceFolder: '_site'
          #     TargetFolder: '$(Build.binariesDirectory)'
          
          # - task: PublishBuildArtifacts@1
          #   inputs:
          #     PathtoPublish: '$(Build.binariesDirectory)'
          #     ArtifactName: site