trigger:
- 'main'

variables:
  releaseBranchName: 'main'
  builderImage: 'jekyll/builder:latest'
  azureServiceConnectionName: 'Dev Subscription (e58a1fd6-05ea-4fac-9e3d-e0d75f25519c)'

stages:
  - stage: 'Build'
    displayName: 'Build the site'
    variables:
      BUILD_INFO: '$(Build.DefinitionName) $(Build.BuildId) $(Build.BuildNumber) - $(Build.SourceBranchName)'
    jobs:
      - job: 'Build'
        displayName: 'Build job'
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: 'Run Jekyll'
            inputs:
              command: run
              arguments: -v $(build.sourcesDirectory):/srv/jekyll:rw -v $(build.sourcesDirectory)/.jekyll-cache:/srv/jekyll/.jekyll-cache:rw -v $(build.binariesDirectory):/srv/jekyll/_site:rw ${{variables.builderImage}} jekyll build --future
          - task: CopyFiles@2
            displayName: 'copy _site'
            inputs:
              SourceFolder: '_site'
              TargetFolder: '$(Build.binariesDirectory)'         
          - task: PublishBuildArtifacts@1
            displayName: 'Publish to dev'
            inputs:
              PathtoPublish: '$(Build.binariesDirectory)'
              ArtifactName: site

  - stage: 'Dev'
    dependsOn: Build
    condition: |
      and
      (
        succeeded(),
        eq(variables['Build.SourceBranchName'], variables['releaseBranchName'])
      )
    displayName: 'Deploy to dev'
    jobs:
      - job: 'DeployDev'
        displayName: 'Deploy job for dev'
        variables:
        - group: Deployment
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Dev Subscription (e58a1fd6-05ea-4fac-9e3d-e0d75f25519c)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: "az storage blob upload-batch -d '$web' -s $(Pipeline.Workspace)/site/* --account-name $(staticSiteStorageAccountName) --account-key $(staticSiteStorageAccountKey)"

     